version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_zakat_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_zakat_app
    command: ["/app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
